# Custom fabric container images
fabric_images:
  ca: hyperledger/fabric-ca:1.5.0
  peer: hyperledger/fabric-peer:2.2.0
  tools: hyperledger/fabric-tools:2.2.0
  orderer: hyperledger/fabric-orderer:2.2.0
  couchdb: hyperledger/fabric-couchdb:0.4.15
  ccenv: hyperledger/fabric-ccenv:2.2.0
caliper_image: hyperledger/caliper:0.4.2

# Fabric Network Config
fabric_num_orgs: 2
fabric_peers_per_org: 2
fabric_num_orderer: 3
fabric_orderer_domain: orgorderer1

# Fabric Orderer Type: Available types are "solo" and "etcdraft"
fabric_orderer_type: etcdraft

# stateDatabase - options are "goleveldb", "CouchDB"
stateDatabase: goleveldb

# Batch Timeout: The amount of time to wait before creating a batch
fabric_batch_timeout: "2s"
# Batch Size: Controls the number of messages batched into a block ["Max Message Count", "Absolute Max Bytes", "Preferred Max Bytes"]
fabric_batchsize: ["500", "98 MB", "2 MB"]
# Enable tls globally in the network
fabric_tls_enabled: false 

# Endorsement policy
endorsement:
  type: "Signature"         # "Signature" or "ImplicitMeta"
  rule: "OR('Org1MSP.member', 'Org2MSP.member')"
  #rule: "OutOf(2, 'Org1MSP.member', 'Org2MSP.member', 'Org3MSP.member')"        # e.g "OR('Org1MSP.member', 'Org2MSP.member')"

# Channel configuration
channels:                   # List of channel objects
  - name: "mychannel"
    chaincodes:
      - id: generator
        contractID: generator               # NOTE: This should be unique for chaincodes across channels
        path: "chaincode/generator/go"      # NOTE: Relative path to Directory where chaincode file is located options: node,go
        language: golang                                      #node, golang
        version: v1
        sequence: 1

      #- id: fixed-asset
      #  contractID: fixed-asset               # NOTE: This should be unique for chaincodes across channels
      #  path: "chaincode/fixed-asset/go"      # NOTE: Relative path to Directory where chaincode file is located options: node,go
      #  language: golang                                      #node, golang
      #  version: v1
      #  sequence: 1

      #- id: simplesupplychain
      #  contractID: simplesupplychain               # NOTE: This should be unique for chaincodes across channels
      #  path: "chaincode/simplesupplychain/go"      # NOTE: Relative path to Directory where chaincode file is located options: node,go
      #  language: golang                                      #node, golang
      #  version: v1
      #  initFunctionName: initLedger
      #  sequence: 1
      #- id: electronic-health-record
      #  contractID: electronic-health-record               # NOTE: This should be unique for chaincodes across channels
      #  path: "chaincode/electronic-health-record/node"      # NOTE: Relative path to Directory where chaincode file is located options: node,go
      #  language: node                                      #node, golang
      #  version: v1
      
# Logging Level
fabric_ca_loglevel: "INFO"
fabric_peer_loglevel: "INFO"
fabric_orderer_loglevel: "INFO"

# use docker credentials
use_docker_credentials: false
