test:
  workers:
    type: local
    number: 3
  rounds:
    - label: InitLedger
      txNumber: 1
      rateControl:
          type: fixed-rate
          opts:
            tps: 1
      workload:
        module: /caliper-workload/InitLedger.js

    - label: common
      txDuration: 10
      rateControl:
          type: fixed-rate
          opts:
            tps: 50
      workload:
        module: /caliper-workload/common.js

    - label: common
      txDuration: 10
      rateControl:
          type: fixed-rate
          opts:
            tps: 50
      workload:
        module: /caliper-workload/common.js

    - label: common
      txDuration: 10
      rateControl:
          type: fixed-rate
          opts:
            tps: 50
      workload:
        module: /caliper-workload/common.js

    - label: common
      txDuration: 10
      rateControl:
          type: fixed-rate
          opts:
            tps: 50
      workload:
        module: /caliper-workload/common.js

    - label: common
      txDuration: 10
      rateControl:
          type: fixed-rate
          opts:
            tps: 50
      workload:
        module: /caliper-workload/common.js

    - label: common
      txDuration: 10
      rateControl:
          type: fixed-rate
          opts:
            tps: 50
      workload:
        module: /caliper-workload/common.js