test:
  workers:
    type: local
    number: 5
  rounds:
    - label: InitLedger
      txNumber: 1
      rateControl:
          type: fixed-rate
          opts:
            tps: 1
      workload:
        module: /caliper-workload/InitLedger.js

    - label: common
      txNumber: 1000
      rateControl:
          type: fixed-rate
          opts:
            tps: 100
      workload:
        module: /caliper-workload/common.js
