hostAliases:
- ip: 10.233.10.121
  hostnames: [orderer0.orgorderer1]
- ip: 10.233.13.223
  hostnames: [orderer1.orgorderer1]
- ip: 10.233.53.57
  hostnames: [orderer2.orgorderer1]
- ip: 10.233.1.58
  hostnames: [peer0.org1]
- ip: 10.233.60.175
  hostnames: [peer1.org1]
- ip: 10.233.20.246
  hostnames: [peer0.org2]
- ip: 10.233.33.234
  hostnames: [peer1.org2]
