hostAliases:
- ip: 10.233.34.40
  hostnames: [orderer0.orgorderer1]
- ip: 10.233.53.127
  hostnames: [orderer1.orgorderer1]
- ip: 10.233.34.6
  hostnames: [orderer2.orgorderer1]
- ip: 10.233.34.148
  hostnames: [peer0.org1]
- ip: 10.233.32.185
  hostnames: [peer1.org1]
- ip: 10.233.42.78
  hostnames: [peer0.org2]
- ip: 10.233.23.3
  hostnames: [peer1.org2]
