hostAliases:
- ip: 10.233.21.182
  hostnames: [orderer0.orgorderer1]
- ip: 10.233.7.78
  hostnames: [orderer1.orgorderer1]
- ip: 10.233.19.85
  hostnames: [orderer2.orgorderer1]
- ip: 10.233.41.22
  hostnames: [peer0.org1]
- ip: 10.233.53.221
  hostnames: [peer1.org1]
- ip: 10.233.60.52
  hostnames: [peer2.org1]
- ip: 10.233.55.141
  hostnames: [peer0.org2]
- ip: 10.233.25.35
  hostnames: [peer1.org2]
- ip: 10.233.51.216
  hostnames: [peer2.org2]
