#ActualRate: Rate needed by the client
#LearnedRate: Rate recommended by the RL system (always < ActualRate), 
#PendingRate: ActualRate-LearnedRate
#MaxRate: Maximum rate supported by the client

w0ActualRate: 100
w0LearnedRate: 60
w0PendingRate: 40
w0MaxRate: 500

w1ActualRate: 100
w1LearnedRate: 60
w1PendingRate: 40
w1MaxRate: 500

w2ActualRate: 100
w2LearnedRate: 60
w2PendingRate: 40
w2MaxRate: 500

w3ActualRate: 100
w3LearnedRate: 60
w3PendingRate: 40
w3MaxRate: 500

w4ActualRate: 100
w4LearnedRate: 60
w4PendingRate: 40
w4MaxRate: 500

w5ActualRate: 100
w5LearnedRate: 60
w5PendingRate: 40
w5MaxRate: 500

w6ActualRate: 100
w6LearnedRate: 60
w6PendingRate: 40
w6MaxRate: 500

w7ActualRate: 100
w7LearnedRate: 60
w7PendingRate: 40
w7MaxRate: 500

w8ActualRate: 100
w8LearnedRate: 60
w8PendingRate: 40
w8MaxRate: 500

w9ActualRate: 100
w9LearnedRate: 60
w9PendingRate: 40
w9MaxRate: 500