test:
  workers:
    type: local
    number: 10

  rounds:
    - label: initLedger
      txNumber: 10000
      rateControl:
          type: fixed-rate
          opts:
            tps: 1000
      workload:
        module: /caliper-workload/initLedger.js

    - label: common
      txDuration: 10
      rateControl:
          type: /caliper-workload/ratecontroller.js
          opts:
            tps: 500
      workload:
        module: /caliper-workload/common.js
    
    - label: common
      txDuration: 10
      rateControl:
          type: /caliper-workload/ratecontroller.js
          opts:
            tps: 500
      workload:
        module: /caliper-workload/common.js

    - label: common
      txDuration: 10
      rateControl:
          type: /caliper-workload/ratecontroller.js
          opts:
            tps: 500
      workload:
        module: /caliper-workload/common.js

    - label: common
      txDuration: 10
      rateControl:
          type: /caliper-workload/ratecontroller.js
          opts:
            tps: 500
      workload:
        module: /caliper-workload/common.js

    - label: common
      txDuration: 10
      rateControl:
          type: /caliper-workload/ratecontroller.js
          opts:
            tps: 500
      workload:
        module: /caliper-workload/common.js

